version: '3'
services:
  jenkins:
    image: cloudsheger/jenkins:lts-k8s
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkinsnet

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - jenkinsnet

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    ports:
      - "8082:8082"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    networks:
      - jenkinsnet

volumes:
  jenkins_data:
  sonarqube_data:
  artifactory_data:

networks:
  jenkinsnet:
